# Generated by Django 2.2.13 on 2021-03-13 00:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20210207_2257'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, default=None, null=True, upload_to='resources/posts/%Y/%m/%d/')),
                ('image', models.ImageField(blank=True, default=None, null=True, upload_to='resources/posts/%Y/%m/%d/')),
                ('link', models.URLField(blank=True, default=None, max_length=512, null=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.Post')),
            ],
        ),
    ]
