# Generated by Django 4.2.7 on 2025-03-03 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_post_ejs_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='ejs_body',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Attachment',
        ),
    ]
