# Generated by Django 2.0.2 on 2020-04-24 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hierarchy', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='department',
        ),
        migrations.AddField(
            model_name='subject',
            name='departments',
            field=models.ManyToManyField(to='hierarchy.Department'),
        ),
    ]
