# Generated by Django 2.0.2 on 2020-04-25 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hierarchy', '0002_auto_20200425_0207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecturer',
            name='department',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='lecturer',
        ),
        migrations.DeleteModel(
            name='Lecturer',
        ),
    ]
