# Generated by Django 2.2.13 on 2021-10-17 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hierarchy', '0003_auto_20200426_0208'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='short_name',
            new_name='vk_id',
        ),
    ]
