# Generated by Django 2.2.13 on 2021-10-17 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hierarchy', '0004_auto_20211017_1916'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='vk_city_id',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
