# Generated by Django 2.0.2 on 2020-10-12 00:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hierarchy', '0003_auto_20200426_0208'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, default='resources/default/user_ava.png', null=True, upload_to='resources/user_avatars/')),
                ('karma', models.SmallIntegerField(default=10)),
                ('course', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('department', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hierarchy.Department')),
            ],
        ),
        migrations.CreateModel(
            name='StudentStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('status_level', models.PositiveSmallIntegerField(default=0)),
                ('can_publish_without_moderation', models.BooleanField(default=False)),
                ('can_moderate', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='studentinfo',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.StudentStatus'),
        ),
        migrations.AddField(
            model_name='studentinfo',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
