# Generated by Django 4.2.7 on 2025-05-18 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_studentinfo_id_alter_studentstatus_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentinfo',
            name='avatar',
        ),
        migrations.AddField(
            model_name='studentinfo',
            name='avatar_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
