services:
  picloud-postgres:
    image: postgres
    container_name: picloud-postgres
    ports:
      - "5432:5432"
    env_file: ./data/db.env
    volumes:
      - ./data/db:/var/lib/postgresql/data

  picloud:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        container_version: ${IMAGE_VERSION:-latest}
    container_name: picloud-app
    volumes:
      - .:/app
    env_file:
      - path: ./data/secrets.env
        required: true
      - path: ./data/db.env
        required: true
    ports:
      - "8000:8000"
    depends_on:
      - picloud-postgres