# Generated by Django 2.0.1 on 2018-01-07 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0002_auto_20180107_0413'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chair',
            name='department',
        ),
        migrations.RemoveField(
            model_name='department',
            name='university',
        ),
        migrations.RemoveField(
            model_name='lecturer',
            name='department',
        ),
        migrations.RemoveField(
            model_name='program',
            name='chair',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='lecturer',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='program',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='program',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='status',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='user',
        ),
        migrations.RemoveField(
            model_name='post',
            name='file',
        ),
        migrations.RemoveField(
            model_name='post',
            name='link',
        ),
        migrations.RemoveField(
            model_name='post',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='post',
            name='type',
        ),
        migrations.RemoveField(
            model_name='post',
            name='validate_status',
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(null=True, upload_to='resources/posts/%Y/%m/%d/'),
        ),
        migrations.DeleteModel(
            name='Chair',
        ),
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.DeleteModel(
            name='Lecturer',
        ),
        migrations.DeleteModel(
            name='PostType',
        ),
        migrations.DeleteModel(
            name='Program',
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
        migrations.DeleteModel(
            name='University',
        ),
        migrations.DeleteModel(
            name='UserInfo',
        ),
        migrations.DeleteModel(
            name='UserStatus',
        ),
    ]
