# Generated by Django 2.0.1 on 2018-01-10 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0002_auto_20180111_0101'),
    ]

    operations = [
        migrations.AddField(
            model_name='chair',
            name='short_title',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='department',
            name='short_title',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='university',
            name='short_title',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
