# Generated by Django 2.0.1 on 2018-01-10 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0003_auto_20180111_0131'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lecturer',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='lecturer',
            old_name='last_name',
            new_name='surname',
        ),
        migrations.AddField(
            model_name='lecturer',
            name='patronymic',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
