# Generated by Django 2.0.2 on 2020-04-25 23:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hierarchy', '0003_auto_20200426_0208'),
        ('cloud', '0003_auto_20191026_1816'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hierarchy',
            name='level',
        ),
        migrations.RemoveField(
            model_name='hierarchy',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='lecturer',
            name='hierarchy',
        ),
        migrations.RemoveField(
            model_name='memesource',
            name='hierarchy',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='hierarchy',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='hierarchy',
        ),
        migrations.AddField(
            model_name='post',
            name='department',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hierarchy.Department'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='department',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hierarchy.Department'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_author', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_post', to='cloud.Post'),
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='post_author', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='last_editor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legacy_last_editor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='parent_post',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legacy_parent_post', to='cloud.Post'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cloud.Program'),
        ),
        migrations.DeleteModel(
            name='Hierarchy',
        ),
        migrations.DeleteModel(
            name='HierarchyLevel',
        ),
    ]
