# Generated by Django 2.0.2 on 2020-04-26 01:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hierarchy', '0003_auto_20200426_0208'),
        ('cloud', '0004_auto_20200426_0208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='department',
        ),
        migrations.AddField(
            model_name='post',
            name='new_subject',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hierarchy.Subject'),
        ),
    ]
