# Generated by Django 2.0.1 on 2018-01-10 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0004_auto_20180111_0144'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturer',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='resources/lec_avatars/'),
        ),
    ]
