# Generated by Django 2.0.2 on 2020-09-22 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0005_auto_20200426_0418'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='new_subject',
        ),
    ]
