# Generated by Django 2.0.2 on 2020-09-23 02:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0006_remove_post_new_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='department',
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legacy_program', to='cloud.Program'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legacy_status', to='cloud.UserStatus'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='legacy_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
