# Generated by Django 2.0.1 on 2018-01-12 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0007_auto_20180111_0202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecturer',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/resources/lec_avatars/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='static/resources/posts/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/resources/posts/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='university',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='static/resources/u_logo/'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='static/resources/user_avatars/'),
        ),
    ]
