# Generated by Django 2.0.1 on 2018-01-13 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0010_auto_20180113_0054'),
    ]

    operations = [
        migrations.AddField(
            model_name='chair',
            name='link',
            field=models.URLField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='department',
            name='link',
            field=models.URLField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='link',
            field=models.URLField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='university',
            name='link',
            field=models.URLField(blank=True, max_length=512, null=True),
        ),
    ]
