# Generated by Django 2.0.1 on 2018-01-14 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0011_auto_20180113_0347'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='program',
        ),
        migrations.AddField(
            model_name='subject',
            name='program',
            field=models.ManyToManyField(to='cloud.Program'),
        ),
    ]
