# Generated by Django 2.0.1 on 2018-01-15 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0012_auto_20180115_0043'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='course',
            new_name='semestr',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='program',
        ),
        migrations.AddField(
            model_name='program',
            name='subjects',
            field=models.ManyToManyField(to='cloud.Subject'),
        ),
    ]
