# Generated by Django 2.0.1 on 2018-01-16 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0014_auto_20180116_0002'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='course',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
