# Generated by Django 2.0.1 on 2018-02-26 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0016_post_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='posttype',
            name='plural',
            field=models.CharField(default='', max_length=128),
        ),
    ]
