# Generated by Django 2.0.3 on 2018-03-30 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0017_posttype_plural'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='validate_status',
            new_name='approved',
        ),
        migrations.AlterField(
            model_name='post',
            name='approved',
            field=models.BooleanField(default=True),
        ),
    ]
