# Generated by Django 2.0.1 on 2018-03-31 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0017_posttype_plural'),
    ]

    operations = [
        migrations.AddField(
            model_name='chair',
            name='validate_status',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='department',
            name='validate_status',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lecturer',
            name='validate_status',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='program',
            name='validate_status',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subject',
            name='validate_status',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='university',
            name='validate_status',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
