# Generated by Django 2.0.3 on 2018-04-08 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0018_auto_20180331_0142'),
        ('cloud', '0018_auto_20180331_0318'),
    ]

    operations = [
    ]
