# Generated by Django 2.0.3 on 2018-04-10 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0021_userstatus_can_publish_without_moderation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='semestr',
            new_name='semester',
        ),
    ]
