# Generated by Django 2.0.3 on 2018-04-12 12:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cloud', '0022_auto_20180410_0309'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='posttype',
            options={'ordering': ['title']},
        ),
        migrations.AddField(
            model_name='post',
            name='last_author',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='last_author',
                to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    to=settings.AUTH_USER_MODEL),
        ),
    ]
