# Generated by Django 2.0.3 on 2018-04-12 13:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cloud', '0023_auto_20180412_1558'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='last_author',
        ),
        migrations.AddField(
            model_name='post',
            name='last_editor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_editor', to=settings.AUTH_USER_MODEL),
        ),
    ]
