# Generated by Django 2.0.1 on 2018-04-17 23:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cloud', '0026_auto_20180417_0206'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(blank=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('chair', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cloud.Chair')),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cloud.Department')),
                ('program', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cloud.Program')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cloud.Subject')),
                ('university', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cloud.University')),
            ],
        ),
    ]
