# Generated by Django 2.0.1 on 2018-04-18 00:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cloud', '0027_memsource'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemeSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(blank=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('chair', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cloud.Chair')),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cloud.Department')),
                ('program', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cloud.Program')),
                ('subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cloud.Subject')),
                ('university', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cloud.University')),
            ],
        ),
        migrations.RemoveField(
            model_name='memsource',
            name='author',
        ),
        migrations.RemoveField(
            model_name='memsource',
            name='chair',
        ),
        migrations.RemoveField(
            model_name='memsource',
            name='department',
        ),
        migrations.RemoveField(
            model_name='memsource',
            name='program',
        ),
        migrations.RemoveField(
            model_name='memsource',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='memsource',
            name='university',
        ),
        migrations.DeleteModel(
            name='MemSource',
        ),
    ]
