# Generated by Django 2.0.1 on 2018-04-18 00:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0028_auto_20180418_0308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memesource',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='memesource',
            name='chair',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cloud.Chair'),
        ),
        migrations.AlterField(
            model_name='memesource',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cloud.Department'),
        ),
        migrations.AlterField(
            model_name='memesource',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cloud.Program'),
        ),
        migrations.AlterField(
            model_name='memesource',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cloud.Subject'),
        ),
        migrations.AlterField(
            model_name='memesource',
            name='university',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cloud.University'),
        ),
    ]
