# Generated by Django 2.0.1 on 2018-06-17 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0030_post_parent_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='vk_id',
            field=models.CharField(max_length=16, null=True),
        ),
    ]
