# Generated by Django 2.0.1 on 2018-06-17 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0031_userinfo_vk_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='vk_id',
            field=models.CharField(default=None, max_length=16, null=True),
        ),
    ]
